### ISSUE TITLE
hola amigos 

### ISSUE THREAD

**Issue by hiddenotebook** [FestCat/festival-ca#5]
He escuchado sus voces en catalán y me he quedado de piedra están muy bien hechas!

No tendrán por ahí documentación para crear la miá propia en castellano me encantaría poder dar a mi robot una voz en condiciones.

Muchas gracias!!

**Comment by zeehio** [comment]
Hola

Disculpa la falta de comunicación.

Para voces de festival lo mejor es seguir las recomendaciones de festvox. No disponemos de documentación propia más allá de lo que encuentres publicado aquí.

El estado del arte en síntesis de voz pasa por usar redes neuronales, con bases de datos mayores, obteniendo voces mucho más naturales. Te recomendaría que buscaras información en proyectos como DeepSpeech de Mozilla, cuya comunidad es mucho mayor.

**Comment by hiddenotebook** [comment]
Muchas gracias por la información 😊
